version: '3'

services:
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: '5000'
    ports:
      - '5000:5000'
